name: Laravel CI/CD

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring,bcmath,intl,pdo_pgsql,zip
          coverage: none

      - name: Install Composer dependencies
        run: |
          composer install \
            --no-interaction \
            --prefer-dist \
            --no-progress

      - name: Prepare environment
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run tests
        run: php artisan test

  build:
    name: Build Docker Images
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build App Image
        run: |
          docker build \
            --tag ghcr.io/sayedtaqi313/laravel_aws-app:latest \
            .

      - name: Build Nginx Image
        run: |
          docker build \
            --tag ghcr.io/sayedtaqi313/laravel_aws-nginx:latest \
            -f docker/nginx/Dockerfile \
            .

      - name: Push App Image
        run: |
          docker push ghcr.io/sayedtaqi313/laravel_aws-app:latest

      - name: Push Nginx Image
        run: |
          docker push ghcr.io/sayedtaqi313/laravel_aws-nginx:latest

  deploy:
    name: Deploy to EC2
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}

          script: |
            set -e

            cd /opt/laravel/laravel_aws

            echo "Pull latest images"

            docker compose pull

            echo "Start containers"

            docker compose up -d

            echo "Run migrations"

            docker compose exec -T app \
              php artisan migrate --force

            echo "Clear Laravel cache"

            docker compose exec -T app \
              php artisan optimize:clear

            echo "Cache Laravel configuration"

            docker compose exec -T app \
              php artisan config:cache

            docker compose exec -T app \
              php artisan route:cache

            docker compose exec -T app \
              php artisan view:cache

            docker compose exec -T app \
              php artisan db:seed              

            echo "Deployment completed"

            docker compose ps
